name: Request

on:
  pull_request:

jobs:
  foo:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
      # Prepare env directory
      - name: Prepare env directory
        run: |
          mkdir -p env
          cp badenv.json env/env.json
          sed -i 's/{TODO_SHA_HERE}/${{ github.event.pull_request.head.sha }}/g' env/env.json
      - name: Deploy Artifact
        uses: actions/upload-artifact@v4
        with:
          name: env
          path: env/